// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKha36Cndt0llx2qBCFgLmd1CHJzMg7zs',
    appId: '1:851788190219:web:29b17f3528d55aebfd2d0e',
    messagingSenderId: '851788190219',
    projectId: 'flutterfinance-a203d',
    authDomain: 'flutterfinance-a203d.firebaseapp.com',
    storageBucket: 'flutterfinance-a203d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0n9rqlh-HKIA3-qHDnOJfZ0Q_IdzsP38',
    appId: '1:851788190219:android:803dadc5522af3dffd2d0e',
    messagingSenderId: '851788190219',
    projectId: 'flutterfinance-a203d',
    storageBucket: 'flutterfinance-a203d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ssdS38xm9CRZ28aqqIJYiS7Gs6SaJsg',
    appId: '1:851788190219:ios:bfe716404c76d43cfd2d0e',
    messagingSenderId: '851788190219',
    projectId: 'flutterfinance-a203d',
    storageBucket: 'flutterfinance-a203d.appspot.com',
    iosClientId: '851788190219-fng02isn0rnt48q79l8g9f7j6n2cui4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ssdS38xm9CRZ28aqqIJYiS7Gs6SaJsg',
    appId: '1:851788190219:ios:f59d00b5b7cb5afafd2d0e',
    messagingSenderId: '851788190219',
    projectId: 'flutterfinance-a203d',
    storageBucket: 'flutterfinance-a203d.appspot.com',
    iosClientId: '851788190219-ia49jhr0frnof3q6162f3l0ho85qf7m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeFlutter.RunnerTests',
  );
}
